//
// Created by 김성준 on 2020/12/17.
//

#ifndef ALGORITHMIC_PROBLEM_SOLVING_STRATEGIES_CODE3_2_H
#define ALGORITHMIC_PROBLEM_SOLVING_STRATEGIES_CODE3_2_H


class code3_2 {

};


#endif //ALGORITHMIC_PROBLEM_SOLVING_STRATEGIES_CODE3_2_H
