//
// Created by 김성준 on 2020/12/17.
//

#ifndef ALGORITHMIC_PROBLEM_SOLVING_STRATEGIES_CODE3_1_H
#define ALGORITHMIC_PROBLEM_SOLVING_STRATEGIES_CODE3_1_H

class code3_1 {

};


#endif //ALGORITHMIC_PROBLEM_SOLVING_STRATEGIES_CODE3_1_H
